// resources/js/PagesVue/Auth/Login.vue
<template>
    <Head title="Log in" />

    <jet-authentication-card>
        <template #logo>
            <jet-authentication-card-logo />
        </template>

        <jet-validation-errors class="mb-4" />

        <div v-if="status" class="mb-4 font-medium text-sm text-green-600">
            {{ status }}
        </div>

        <form @submit.prevent="submit">
            <div>
                <jet-label for="email" value="Email" />
                <jet-input id="email" type="email" class="mt-1 block w-full" v-model="form.email" required autofocus />
            </div>

            <div class="mt-4">
                <jet-label for="password" value="Password" />
                <jet-input id="password" type="password" class="mt-1 block w-full" v-model="form.password" required autocomplete="current-password" />
            </div>

            <div class="block mt-4">
                <label class="flex items-center">
                    <jet-checkbox name="remember" v-model:checked="form.remember" />
                    <span class="ml-2 text-sm text-gray-600">Remember me</span>
                </label>
            </div>

            <div class="flex items-center justify-end mt-4">
                <Link v-if="canResetPassword" :href="route('password.request')" class="underline text-sm text-gray-600 hover:text-gray-900">
                    Forgot your password?
                </Link>

                <jet-button class="ml-4" :class="{ 'opacity-25': form.processing }" :disabled="form.processing">
                    Log in
                </jet-button>
            </div>
        </form>
    </jet-authentication-card>
</template>

<script>
    import { defineComponent } from 'vue'
    import JetAuthenticationCard from '@/JetstreamVue/AuthenticationCard.vue'
    import JetAuthenticationCardLogo from '@/JetstreamVue/AuthenticationCardLogo.vue'
    import JetButton from '@/JetstreamVue/Button.vue'
    import JetInput from '@/JetstreamVue/Input.vue'
    import JetCheckbox from '@/JetstreamVue/Checkbox.vue'
    import JetLabel from '@/JetstreamVue/Label.vue'
    import JetValidationErrors from '@/JetstreamVue/ValidationErrors.vue'
    import { Head, Link } from '@inertiajs/inertia-vue3';

    export default defineComponent({
        components: {
            Head,
            JetAuthenticationCard,
            JetAuthenticationCardLogo,
            JetButton,
            JetInput,
            JetCheckbox,
            JetLabel,
            JetValidationErrors,
            Link,
        },

        props: {
            canResetPassword: Boolean,
            status: String
        },

        data() {
            return {
                form: this.$inertia.form({
                    email: '',
                    password: '',
                    remember: false
                })
            }
        },

        methods: {
            submit() {
                this.form
                    .transform(data => ({
                        ... data,
                        remember: this.form.remember ? 'on' : ''
                    }))
                    .post(this.route('login'), {
                        onFinish: () => this.form.reset('password'),
                    })
            }
        }
    })
</script>

// resources/js/Pages/Auth/Login.svelte
<script context="module">
    import Layout from '@/Layouts/App.svelte'
    export const layout = Layout
</script>

<script>
    import { Inertia } from '@inertiajs/inertia';
    import { useForm } from '@inertiajs/inertia-svelte';

    let form = useForm({
        email: '',
        password: '',
    });

    let submit = () => {
        $form.post(route('login'));
    };
</script>


<form class="space-y-4">
    <section class="text-lg font-bold">Login</section>
    <section class="flex flex-col">
        <label for="email">Email</label>
        <input class="border border-gray-400 focus:border-blue-400 outline-none rounded px-4 py-2" bind:value={$form.email} type="email" id="email" name="email" />
        {#if $form.errors.email}
            <div class="text-sm text-red-500">
                { $form.errors.email }
            </div>
        {/if}
    </section>
    <section class="flex flex-col">
        <label for="password">Password</label>
        <input class="border border-gray-400 focus:border-blue-400 outline-none rounded px-4 py-2" bind:value={$form.password} type="password" id="password" name="password" />
        {#if $form.errors.password}
            <div class="text-sm text-red-500">
                { $form.errors.password }
            </div>
        {/if}
    </section>
    <section class="flex justify-end">
        <button class="rounded px-4 py-2 text-white bg-green-700 hover:bg-green-500" on:click|preventDefault={submit} disabled={$form.processing}>Login</button>
    </section>
</form>
